version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: precedence-app
    ports:
      - "80:80"
      - "8000:8000"
      - "3001:3001"
    volumes:
      - .:/workspace:cached
      - ./.git:/workspace/.git:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - COURTLISTENER_API_TOKEN=${COURTLISTENER_API_TOKEN}
      - PROJECT_ROOT=/workspace
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: precedence-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data: