version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    env_file:
      - .env
      - frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - .env
      - backend/.env
    environment:
      - CASE_LAW_API_KEY=${CASE_LAW_API_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge